6,a,pre fc  fcati
1,m,pre kal kalate
10,a,pre kup kopayati
10,m,pre kF kArayate
1,m,pre kvaT kvaTate
10,a,pre kzap kzapayati
1,a,pre kzE kzAyati
10,m,pre gF gArayate
1,m,pre cal calate
1,m,pre cumb cumbate
10,a,pre cumb cumbayati
1,m,pre jap japate
1,m,pre jIv jIvate
1,a,pre tan tanati
10,a,pre tan tAnayati
4,m,pre tam tAmyate
1,m,pre tarj tarjate
1,a,pre tij tejati
10,a,pre tras trAsayati 
10,a,pre div devayati
10,m,pre div devayate
1,a,pre duh dohati
6,a,pre dfp dfpati dfmpati 
6,a,pre dfp dfmpati 
1,a,pre drA drAyati
1,m,pre drA drAyate
1,m,pre nu navate
1,a,pre pad padati 
4,m,pre pI pIyate
6,m,pre pf priyate 
10,a,pre praT prATayati parTayati
10,a,pre praT prATayati
1,a,pre pruz prozati
10,a,pre BaYj BaYjayati
1,a,pre mid medati
1,a,pre miz mezati
1,a,pre mI mayati 
10,a,pre mI mAyayati
1,m,pre muc mocate
10,a,pre mud modayati
1,a,pre mlE mlAyati mlAti
1,a,pre mlE mlAti
10,a,pre raR raRayati
4,a,pre vas  vasyati
1,a,pre viS  veSati
1,a,pre Siz  Sezati
4,m,pre SI   SIyate
1,a,pre Sliz Slezati
4,a,pre sah sahyati
1,m,pre su  savate
