name: Feature request
description: Request a new capability
title: "[feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: What would you like?
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Why is this needed?
